ALTER SESSION SET CONTAINER = XEPDB1;

SHOW CON_NAME;

--inserts estados
INSERT INTO FIDE_ESTADO_TB (DESCRIPCION)
VALUES ('ACTIVO');
INSERT INTO FIDE_ESTADO_TB (DESCRIPCION)
VALUES ('INACTIVO');

COMMIT;

--inserts de turnos prueba crud
INSERT INTO FIDE_TURNOS_TB (HORA_INICIO, HORA_FIN, ID_ESTADO)
VALUES (TO_DATE('08:00', 'HH24:MI'),TO_DATE('16:00', 'HH24:MI'),
(SELECT ID_ESTADO FROM FIDE_ESTADO_TB WHERE DESCRIPCION = 'ACTIVO')
);

COMMIT;



