CREATE OR REPLACE PACKAGE FIDE_PROYECTO_FINAL_PKG AS
-- Módulo Empleados
-- Funciones
FUNCTION FIDE_ESTADO_TB_OBTENER_ID_ESTADO_FN(p_descripcion VARCHAR2) RETURN NUMBER;
FUNCTION FIDE_EMPLEADOS_FUNCION_TB_OBTENER_ID_FUNCION_FN(p_nombre_funcion VARCHAR2) RETURN NUMBER;
FUNCTION FIDE_TURNOS_TB_OBTENER_ID_TURNO_FN(p_inicio DATE, p_fin DATE) RETURN NUMBER;
FUNCTION FIDE_EMPLEADOS_TB_OBTENER_ID_EMPLEADO_FN(p_correo IN VARCHAR2) RETURN NUMBER;

-- Procedimientos
PROCEDURE FIDE_ESTADO_TB_LISTAR_ESTADOS_SP(p_cursor OUT SYS_REFCURSOR);
PROCEDURE FIDE_EMPLEADOS_TB_INSERTAR_EMPLEADO_SP(
    p_nombre IN VARCHAR2,
    p_apellido IN VARCHAR2,
    p_correo IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_fecha IN DATE,
    p_salario IN NUMBER,
    p_funcion_nombre IN VARCHAR2,
    p_hora_inicio IN TIMESTAMP,
    p_hora_fin IN TIMESTAMP,
    p_estado_nombre IN VARCHAR2
);
PROCEDURE FIDE_EMPLEADOS_TB_ACTUALIZAR_EMPLEADO_SP(
    p_nombre IN VARCHAR2,
    p_apellido IN VARCHAR2,
    p_correo IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_fecha IN DATE,
    p_salario IN NUMBER,
    p_funcion_nombre IN VARCHAR2,
    p_hora_inicio IN TIMESTAMP,
    p_hora_fin IN TIMESTAMP,
    p_estado_nombre IN VARCHAR2
);
PROCEDURE FIDE_EMPLEADOS_TB_ELIMINAR_EMPLEADO_SP(p_correo IN VARCHAR2);
PROCEDURE FIDE_EMPLEADOS_TB_LISTAR_EMPLEADOS_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_TURNOS_TB_INSERTAR_TURNO_SP(
    p_hora_inicio IN TIMESTAMP,
    p_hora_fin IN TIMESTAMP,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_TURNOS_TB_ELIMINAR_TURNO_SP(
    p_hora_inicio IN TIMESTAMP,
    p_hora_fin IN TIMESTAMP
);
PROCEDURE FIDE_TURNOS_TB_ACTUALIZAR_TURNO_SP(
    p_hora_inicio IN TIMESTAMP,
    p_hora_fin IN TIMESTAMP,
    p_nueva_hora_inicio IN TIMESTAMP,
    p_nueva_hora_fin IN TIMESTAMP,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_TURNOS_TB_LISTAR_TURNOS_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_EMPLEADOS_FUNCION_TB_INSERTAR_SP(
    p_nombre_funcion IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_EMPLEADOS_FUNCION_TB_ACTUALIZAR_SP(
    p_nombre_funcion_actual IN VARCHAR2,
    p_nuevo_nombre_funcion IN VARCHAR2,
    p_nueva_descripcion IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_EMPLEADOS_FUNCION_TB_INACTIVAR_SP(p_nombre_funcion IN VARCHAR2);
PROCEDURE FIDE_EMPLEADOS_FUNCION_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_VACACIONES_TB_INSERTAR_SP(
    p_fecha IN DATE,
    p_correo IN VARCHAR2,
    p_nombre_funcion IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_VACACIONES_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_VACACIONES_TB_ACTUALIZAR_SP(
    p_correo IN VARCHAR2,
    p_fecha IN DATE,
    p_nueva_fecha IN DATE,
    p_nueva_funcion IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_VACACIONES_TB_INACTIVAR_SP(
    p_correo IN VARCHAR2,
    p_fecha IN DATE
);
PROCEDURE FIDE_EMPLEADOS_TB_LISTAR_CORREOS_SP(p_cursor OUT SYS_REFCURSOR);

-- Módulo Reservas
PROCEDURE FIDE_RESERVAS_TB_INSERTAR_SP(
    p_cliente_nombre IN VARCHAR2,
    p_empleado_correo IN VARCHAR2,
    p_servicio_nombre IN VARCHAR2,
    p_fecha_hora IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_RESERVAS_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_RESERVAS_TB_INACTIVAR_SP(p_id_reserva IN NUMBER);
PROCEDURE FIDE_RESERVAS_TB_ACTUALIZAR_SP(
    p_id_reserva IN NUMBER,
    p_cliente_nombre IN VARCHAR2,
    p_empleado_correo IN VARCHAR2,
    p_servicio_nombre IN VARCHAR2,
    p_fecha_hora IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_CLIENTES_TB_LISTAR_NOMBRES_SP(p_cursor OUT SYS_REFCURSOR);
PROCEDURE FIDE_SERVICIOS_TB_LISTAR_NOMBRES_SP(p_resultado OUT SYS_REFCURSOR);

-- Módulo Dirección
PROCEDURE FIDE_PROVINCIA_TB_INSERTAR_PROVINCIA_SP(
    p_nombre_provincia IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_PROVINCIA_TB_LISTAR_PROVINCIAS_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_PROVINCIA_TB_ACTUALIZAR_PROVINCIA_SP(
    p_nombre_actual IN VARCHAR2,
    p_nuevo_nombre IN VARCHAR2,
    p_nuevo_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_PROVINCIA_TB_INACTIVAR_PROVINCIA_SP(p_nombre_provincia IN VARCHAR2);
FUNCTION FIDE_PROVINCIA_TB_OBTENER_ID_PROVINCIA_FN(p_nombre_provincia IN VARCHAR2) RETURN NUMBER;
PROCEDURE FIDE_CANTON_TB_INSERTAR_SP(
    p_nombre_canton IN VARCHAR2,
    p_provincia_nombre IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_CANTON_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_CANTON_TB_ACTUALIZAR_SP(
    p_nombre_actual IN VARCHAR2,
    p_nuevo_nombre IN VARCHAR2,
    p_nueva_provincia_nombre IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_CANTON_TB_INACTIVAR_SP(p_nombre_canton IN VARCHAR2);
FUNCTION FIDE_CANTON_TB_OBTENER_ID_CANTON_FN(p_nombre_canton IN VARCHAR2) RETURN NUMBER;
PROCEDURE FIDE_DISTRITO_TB_INSERTAR_SP(
    p_nombre_distrito IN VARCHAR2,
    p_nombre_canton IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_DISTRITO_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_DISTRITO_TB_ACTUALIZAR_SP(
    p_nombre_actual IN VARCHAR2,
    p_nuevo_nombre IN VARCHAR2,
    p_nuevo_canton_nombre IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_DISTRITO_TB_INACTIVAR_SP(p_nombre_distrito IN VARCHAR2);
FUNCTION FIDE_DISTRITO_TB_OBTENER_ID_DISTRITO_FN(p_nombre_distrito IN VARCHAR2) RETURN NUMBER;
FUNCTION FIDE_PROVINCIA_TB_LISTAR_ACTIVAS_FN RETURN SYS_REFCURSOR;
FUNCTION FIDE_CANTON_TB_LISTAR_ACTIVOS_FN RETURN SYS_REFCURSOR;
FUNCTION FIDE_DISTRITO_TB_LISTAR_ACTIVOS_FN RETURN SYS_REFCURSOR;
PROCEDURE FIDE_DIRECCION_TB_INSERTAR_SP(
    p_provincia_nombre IN VARCHAR2,
    p_canton_nombre IN VARCHAR2,
    p_distrito_nombre IN VARCHAR2,
    p_estado_nombre IN VARCHAR2
);
PROCEDURE FIDE_DIRECCION_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_DIRECCION_TB_ACTUALIZAR_SP(
    p_id_direccion IN NUMBER,
    p_provincia_nombre IN VARCHAR2,
    p_canton_nombre IN VARCHAR2,
    p_distrito_nombre IN VARCHAR2,
    p_estado_nombre IN VARCHAR2
);
PROCEDURE FIDE_DIRECCION_TB_INACTIVAR_SP(p_id_direccion IN NUMBER);
FUNCTION FIDE_DIRECCION_TB_OBTENER_ID_DIRECCION_FN(p_descripcion VARCHAR2) RETURN NUMBER;
FUNCTION FIDE_DIRECCION_TB_LISTAR_COMO_DESCRIPCION_FN RETURN SYS_REFCURSOR;
FUNCTION FIDE_DIRECCION_TB_OBTENER_PROVINCIA_FN(p_id_direccion IN NUMBER) RETURN VARCHAR2;
FUNCTION FIDE_DIRECCION_TB_OBTENER_CANTON_FN(p_id_direccion IN NUMBER) RETURN VARCHAR2;
FUNCTION FIDE_DIRECCION_TB_OBTENER_DISTRITO_FN(p_id_direccion IN NUMBER) RETURN VARCHAR2;
PROCEDURE FIDE_DIRECCION_TB_LISTAR_DESCRIPCIONES_SP(p_result OUT SYS_REFCURSOR);

-- Módulo Clientes
PROCEDURE FIDE_CLIENTES_TB_INSERTAR_SP(
    p_nombre_cliente IN VARCHAR2,
    p_telefono_cliente IN VARCHAR2,
    p_correo_cliente IN VARCHAR2,
    p_fecha_registro IN VARCHAR2,
    p_direccion_desc IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_CLIENTES_TB_LISTAR_SP(p_result OUT SYS_REFCURSOR);
PROCEDURE FIDE_CLIENTES_TB_ACTUALIZAR_SP(
    p_id_cliente IN NUMBER,
    p_nombre_cliente IN VARCHAR2,
    p_telefono_cliente IN VARCHAR2,
    p_correo_cliente IN VARCHAR2,
    p_fecha_registro IN VARCHAR2,
    p_direccion_desc IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_CLIENTES_TB_INACTIVAR_SP(p_id_cliente IN NUMBER);
FUNCTION FIDE_CLIENTES_TB_OBTENER_ID_CLIENTE_FN(p_nombre_cliente IN VARCHAR2) RETURN NUMBER;

-- Módulo Servicios
PROCEDURE FIDE_SERVICIOS_TB_INSERTAR_SP(
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_precio IN NUMBER,
    p_estado IN VARCHAR2
);
PROCEDURE FIDE_SERVICIOS_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_SERVICIOS_TB_ACTUALIZAR_SP(
    p_nombre_original IN VARCHAR2,
    p_nombre_nuevo IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_precio IN NUMBER,
    p_estado IN VARCHAR2
);
PROCEDURE FIDE_SERVICIOS_TB_INACTIVAR_SP(p_nombre IN VARCHAR2);
FUNCTION FIDE_SERVICIOS_TB_OBTENER_ID_SERVICIO_FN(p_nombre_servicio IN VARCHAR2) RETURN NUMBER;

-- Módulo Beneficios
PROCEDURE FIDE_BENEFICIO_TB_INSERTAR_SP(
    p_detalle_beneficio IN VARCHAR2,
    p_nombre_servicio IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_BENEFICIO_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_BENEFICIO_TB_ACTUALIZAR_SP(
    p_detalle_actual IN VARCHAR2,
    p_detalle_nuevo IN VARCHAR2,
    p_nombre_servicio IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_BENEFICIO_TB_INACTIVAR_SP(p_detalle_beneficio IN VARCHAR2);

-- Módulo Productos
PROCEDURE FIDE_PRODUCTO_TB_INSERTAR_SP(
    p_nombre_producto IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_precio_unitario IN NUMBER,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_PRODUCTO_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_PRODUCTO_TB_ACTUALIZAR_SP(
    p_id_producto IN NUMBER,
    p_nuevo_nombre IN VARCHAR2,
    p_nueva_descripcion IN VARCHAR2,
    p_nuevo_precio IN NUMBER,
    p_nuevo_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_PRODUCTO_TB_INACTIVAR_SP(p_id_producto IN NUMBER);
FUNCTION FIDE_PRODUCTO_TB_OBTENER_ID_PRODUCTO_FN(p_nombre_producto VARCHAR2) RETURN NUMBER;
PROCEDURE FIDE_PRODUCTO_TB_LISTAR_NOMBRES_SP(p_resultado OUT SYS_REFCURSOR);

-- Módulo Inventario
PROCEDURE FIDE_INVENTARIO_TB_INSERTAR_SP(
    p_nombre_producto IN VARCHAR2,
    p_cantidad IN NUMBER,
    p_fecha_actualizacion IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_INVENTARIO_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_INVENTARIO_TB_ACTUALIZAR_SP(
    p_id_inventario IN NUMBER,
    p_nuevo_producto IN VARCHAR2,
    p_nueva_cantidad IN NUMBER,
    p_nueva_fecha IN VARCHAR2,
    p_nuevo_estado IN VARCHAR2
);
PROCEDURE FIDE_INVENTARIO_TB_INACTIVAR_SP(p_id_inventario IN NUMBER);

-- Módulo Proveedores
PROCEDURE FIDE_PROVEEDOR_TB_INSERTAR_SP(
    p_nombre IN VARCHAR2,
    p_contacto IN VARCHAR2,
    p_tipo IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_PROVEEDOR_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_PROVEEDOR_TB_ACTUALIZAR_SP(
    p_id_proveedor IN NUMBER,
    p_nuevo_nombre IN VARCHAR2,
    p_nuevo_contacto IN VARCHAR2,
    p_nuevo_tipo IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_PROVEEDOR_TB_INACTIVAR_SP(p_id_proveedor IN NUMBER);
FUNCTION FIDE_PROVEEDOR_TB_OBTENER_ID_PROVEEDOR_FN(p_nombre VARCHAR2) RETURN NUMBER;
PROCEDURE FIDE_PROVEEDOR_TB_LISTAR_NOMBRES_SP(p_resultado OUT SYS_REFCURSOR);

-- Módulo Órdenes de Compra
PROCEDURE FIDE_ORDENES_COMPRA_TB_INSERTAR_SP(
    p_nombre_proveedor IN VARCHAR2,
    p_fecha_orden IN VARCHAR2,
    p_total IN NUMBER,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_ORDENES_COMPRA_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_ORDENES_COMPRA_TB_ACTUALIZAR_SP(
    p_id_orden IN NUMBER,
    p_nombre_proveedor IN VARCHAR2,
    p_fecha_orden IN VARCHAR2,
    p_total IN NUMBER,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_ORDENES_COMPRA_TB_INACTIVAR_SP(p_id_orden IN NUMBER);

-- Módulo Facturación
PROCEDURE FIDE_METODO_PAGO_TB_INSERTAR_SP(
    p_nombre_metodo IN VARCHAR2,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_METODO_PAGO_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_METODO_PAGO_TB_ACTUALIZAR_SP(
    p_id_metodo_pago IN NUMBER,
    p_nuevo_nombre IN VARCHAR2,
    p_nuevo_estado IN VARCHAR2
);
PROCEDURE FIDE_METODO_PAGO_TB_INACTIVAR_SP(p_id_metodo_pago IN NUMBER);
FUNCTION FIDE_METODO_PAGO_TB_OBTENER_ID_METODO_PAGO_FN(p_nombre_metodo VARCHAR2) RETURN NUMBER;

-- Módulo Historial de Pagos
PROCEDURE FIDE_HISTORIAL_PAGOS_TB_INSERTAR_SP(
    p_nombre_cliente IN VARCHAR2,
    p_monto IN NUMBER,
    p_fecha_pago IN DATE,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_HISTORIAL_PAGOS_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_HISTORIAL_PAGOS_TB_ACTUALIZAR_SP(
    p_id_pago IN NUMBER,
    p_monto IN NUMBER,
    p_fecha_pago IN DATE,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_HISTORIAL_PAGOS_TB_INACTIVAR_SP(p_id_pago IN NUMBER);

-- Módulo Facturas
PROCEDURE FIDE_FACTURAS_TB_INSERTAR_SP(
    p_nombre_cliente IN VARCHAR2,
    p_nombre_metodo_pago IN VARCHAR2,
    p_fecha_emision IN DATE,
    p_total IN NUMBER,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_FACTURAS_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_FACTURAS_TB_ACTUALIZAR_SP(
    p_id_factura IN NUMBER,
    p_total IN NUMBER,
    p_fecha_emision IN DATE,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_FACTURAS_TB_INACTIVAR_SP(p_id_factura IN NUMBER);
FUNCTION FIDE_FACTURAS_TB_OBTENER_ID_FACTURA_FN(p_id_factura IN VARCHAR2) RETURN NUMBER;

-- Módulo Detalle Facturas
PROCEDURE FIDE_DETALLE_FACTURAS_TB_INSERTAR_SP(
    p_id_factura_str IN VARCHAR2,
    p_nombre_producto IN VARCHAR2,
    p_subtotal IN NUMBER,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_DETALLE_FACTURAS_TB_LISTAR_SP(p_resultado OUT SYS_REFCURSOR);
PROCEDURE FIDE_DETALLE_FACTURAS_TB_ACTUALIZAR_SP(
    p_id_detalle IN NUMBER,
    p_subtotal IN NUMBER,
    p_estado_desc IN VARCHAR2
);
PROCEDURE FIDE_DETALLE_FACTURAS_TB_INACTIVAR_SP(p_id_detalle IN NUMBER);

-- Módulo Login
PROCEDURE FIDE_USUARIOS_TB_LOGIN_SP(
    p_usuario IN VARCHAR2,
    p_clave IN VARCHAR2,
    p_id_usuario OUT NUMBER,
    p_rol OUT VARCHAR2,
    p_valido OUT NUMBER
);
PROCEDURE FIDE_LOGIN_VALIDAR_USUARIO_SP(
    p_usuario IN VARCHAR2,
    p_clave IN VARCHAR2,
    p_id_usuario OUT NUMBER,
    p_rol OUT VARCHAR2,
    p_valido OUT NUMBER
);

-- Función auxiliar común
FUNCTION FIDE_ESTADO_TB_OBTENER_ID_ESTADO_FN(p_descripcion VARCHAR2) RETURN NUMBER;

END FIDE_PROYECTO_FINAL_PKG;
/