ALTER SESSION SET CONTAINER = XEPDB1;

SHOW CON_NAME;

--inserts estados
INSERT INTO FIDE_ESTADO_TB (DESCRIPCION)
VALUES ('ACTIVO');
INSERT INTO FIDE_ESTADO_TB (DESCRIPCION)
VALUES ('INACTIVO');

COMMIT;

--inserts de turnos prueba crud
INSERT INTO FIDE_TURNOS_TB (HORA_INICIO, HORA_FIN, ID_ESTADO)
VALUES (TO_DATE('08:00', 'HH24:MI'),TO_DATE('16:00', 'HH24:MI'),
(SELECT ID_ESTADO FROM FIDE_ESTADO_TB WHERE DESCRIPCION = 'ACTIVO')
);

COMMIT;



select * from FIDE_ROL_TB;
select * from FIDE_USUARIOS_TB;


INSERT INTO FIDE_ROL_TB (ID_ROL, NOMBRE_ROL, ID_ESTADO)
VALUES (2, 'EMPLEADO', (SELECT ID_ESTADO FROM FIDE_ESTADO_TB WHERE DESCRIPCION = 'ACTIVO'));

INSERT INTO FIDE_ROL_TB (ID_ROL, NOMBRE_ROL, ID_ESTADO)
VALUES (3, 'CLIENTE', (SELECT ID_ESTADO FROM FIDE_ESTADO_TB WHERE DESCRIPCION = 'ACTIVO'));

INSERT INTO FIDE_ROL_TB (ID_ROL, NOMBRE_ROL, ID_ESTADO)
VALUES (1, 'ADMIN', (SELECT ID_ESTADO FROM FIDE_ESTADO_TB WHERE DESCRIPCION = 'ACTIVO'));




INSERT INTO FIDE_USUARIOS_TB (
    ID_USUARIO, USUARIO, CLAVE, ID_ROL, ID_ESTADO
) VALUES (
    1, 'ADMIN', 'admin123', 23, (SELECT ID_ESTADO FROM FIDE_ESTADO_TB WHERE DESCRIPCION = 'ACTIVO')
);
INSERT INTO FIDE_USUARIOS_TB (
    ID_USUARIO, USUARIO, CLAVE, ID_ROL, ID_ESTADO
) VALUES (
    1, 'cliente', 'cliente123', 22, (SELECT ID_ESTADO FROM FIDE_ESTADO_TB WHERE DESCRIPCION = 'ACTIVO')
);
INSERT INTO FIDE_USUARIOS_TB (
    ID_USUARIO, USUARIO, CLAVE, ID_ROL, ID_ESTADO
) VALUES (
    1, 'empleado', 'empleado123', 21, (SELECT ID_ESTADO FROM FIDE_ESTADO_TB WHERE DESCRIPCION = 'ACTIVO')
);

SELECT * FROM FIDE_USUARIOS_TB WHERE USUARIO = 'cliente';
